/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.restassured.RestAssured;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class AppTestGet {

    @BeforeClass
    public void setUp() {
        RestAssured.baseURI = "https://dummyapi.io/data/v1";
        RestAssured.basePath = "/user";
    }

    @Test
    public void testGetUserByIdValidAndRegistered() {
        given()
                .header("app-id", "662e0effbb70a725c32592e9")
                .pathParam("userId", "60d0fe4f5311236168a109cb") // User ID valid dan terdaftar
                .when()
                .get("/{userId}")
                .then()
                .statusCode(200)
                .body("id", equalTo("60d0fe4f5311236168a109cb"))
                .body("firstName", notNullValue())
                .body("lastName", notNullValue())
                .body("email", notNullValue());
    }

    @Test
    public void testGetUserByIdValidButNotRegistered() {
        given()
                .header("app-id", "662e0effbb70a725c32592e9")
                .pathParam("userId", "60d0fe4f5311236168a202ca") // User ID valid tapi tidak terdaftar
                .when()
                .get("/{userId}")
                .then()
                .statusCode(404); // Not Found
    }

    @Test
    public void testGetUserByIdInvalidFormat() {
        given()
                .header("app-id", "662e0effbb70a725c32592e9")
                .pathParam("userId", "60d0fe4f5") // Format User ID tidak valid
                .when()
                .get("/{userId}")
                .then()
                .statusCode(400); // Bad Request
    }

    @Test
    public void testGetUserByIdWithoutAppIdHeader() {
        given()
                .pathParam("userId", "60d0fe4f5311236168a109cb") // User ID valid dan terdaftar
                .when()
                .get("/{userId}")
                .then()
                .statusCode(403); // Unauthorized
    }

    @Test
    public void testGetUserByIdWithInvalidAppIdHeader() {
        given()
                .header("app-id", "662e0effbb70a725c3259220")
                .pathParam("userId", "60d0fe4f5311236168a109cb") // User ID valid dan terdaftar
                .when()
                .get("/{userId}")
                .then()
                .statusCode(403); // Unauthorized
    }
}
